# .github/workflows/main.yml
name: Python Hello World Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Run the job on the latest Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Check out the repository code

    - name: Set up Python
      uses: actions/setup-python@v4  # Set up Python version
      with:
        python-version: '3.x'  # Use the latest version of Python 3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip
        # You can add other dependencies here if needed
        # e.g., pip install -r requirements.txt

    - name: Run hello.py
      run: |
        ls -lrt
        python hello.py  # Run the Python script
